### ISSUE TITLE
デザインを作成する

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapc2012-ltthon#1]
とりあえずのデザインを作成し、ダミーテキストにてサイトを作成する。

**Comment by uzulla** [comment]
テキストについては、
・キャッチ的なもの、400文字程度
が来ます。

今日中に文面アップという話がありましたが、Charsbarさんがこれから作成するので、
仮文字か、もしくは適当ななテキスト(text_aboutなど)からひっぱって作成してください。

オビテキストは、とりあえずuzulla 「LTをやると色々はかどるぞ！」とかにしておいてください。

**Comment by uzulla** [comment]
帯テキストについて、デザイン上どれくらいの文字数がいいかはちょっとかんがえましょう。
実際の本も参考にすると、大きめな文字で20文字(二行)、小さめなら40文字くらいかなとおもっていますが。

サイトの色について、ほとんどはなしていませんでしたが、YAPCサイトにある色を基調に、
なにか特別な(つかわれていない)差し色が一個あるといいですね。

**Comment by uzulla** [comment]
デザインいいかんじですね、我ながら（本当の意味で我ながら）帯のインパクトすごいｗｗｗ

一点、LTの表はわりと組み替えとか、中に入るテキストの長さとか替わりそうなので、 付箋風まで綺麗につくっちゃうと色々直していくのが大丈夫かな感ありますね（どういう風にHTMLに組んでいくか、でしょうけど）
めくれてないのに（四角なのに）陰ができてる｢偽陰」ならいいかも。

あと、一日目と二日目で、時刻スロットが同一にならないと（多分）思うので、
二日分を横にならべないで、縦にしちゃってOKです。

**Comment by partynight12th** [comment]
付箋風のイメージをCSS3で表現してみました。
http://jsdo.it/kkotaro0111/jdUJ

IE9(win)/Firefox(w/m)/Chrome(w/m)/Safari(mac)でテストした結果、ちゃんとイメージ通りになっているし、
HTMLコード自体はごくシンプルに済んでいるので、
修正も楽かと思います。
どうでしょう。

OKなら付箋続行でいきたいなーと。

**Comment by uzulla** [comment]
残念なおしらせですが、俺のFxだとちょっとおかしいｗ
Firefox 14.0.1 Macで
左下切れてる
http://yairc.cfe.jp:5000/image/4d00cc793314d61cf9f55fa71b266b9c.png

**Comment by partynight12th** [comment]
Fxだと、transform: skew(0,2deg);が効かなくて、仕方なくrotate(2deg)使ってるのが原因ですね。
うーん、別の方法を探すしかないかなー。

**Comment by uzulla** [comment]
HTML作成有り難うございます！

何点か、
・LT作成方法のページ、JSで切り換えできますが、ここパーマリンクほしいので、独立させてください。
・トップの説明文章、もうちょっと可読性のあるフォントでもよいのでは…趣味か。
・ヘッダーの「詳細」については、なんか言い換えがほしいですね。トップ、でもいいんですけど。
・帯は、ページの下部にposition FIXできます？（うざい感がもっとほしい）その都合で、もうちょっと縦小さくしたほうがいいかなと。

**Comment by partynight12th** [comment]
・LT作成方法を2ページに分ける　→　対応しました。
・トップの説明文章のフォント変える　→　もう少しデザイン詰めたい感あるので、おいおい対応します。
・ヘッダーの「詳細」を「トップ」にする　→　TOPにしました。テキストなので、状況に応じてすぐ変えられます。
・帯をposition:fixed;化　→　対応しました。縦幅についてですが、この帯の内容が決まり次第なところもあるので、とりまこのままにしておきます。

**Comment by uzulla** [comment]
諸々了解、

帯ゆーすけべー氏に原稿依頼しました。もどってきたらレスります。
とりあえず、100文字前後で、アー写もください、という感じでやってます。

あと、帯ですが、どっかのタイミングで「帯を捨てる」とかで、消せるようにしておいてくださいｗ
（リロードで復活可、ベターなのはCookieに保存）

**Comment by partynight12th** [comment]
了解です。他のデータが揃いつつ、修正を入れる段階で組み立てます。

**Comment by partynight12th** [comment]
帯ですが、５，６人に声かけられないですかね。
ページ開くたびに、違うメッセージが見えたほうが面白いかな、と。
ゆーすけべーさん、uzullaさんで２人、あと３，４人。

**Comment by uzulla** [comment]
それは勿論あって、今後増やしていく予定です（俺ははいってなかったんですけど、まあいれとくか…誰やねんだけど）

**Comment by uzulla** [comment]
とりあえず俺原稿書いた
「LTはいつも興味深く楽しい、でもそろそろLTも進化するべきではないか。単に短い発表という枠を超え、LTをもっと双方向のコミュニケーションにしたい、私はそう思っています。その為に今回、一風変わったLTのイベントをやる事にしました。」
多分レイアウトの都合上画像になってますけど、手間など考えると文字ベースにした方が良いのでは？（でもインパクト減るかなーー）

**Comment by partynight12th** [comment]
了解しましたー
ちょっと文字ベースの場合どうするか、考えておきます。

**Comment by uzulla** [comment]
まあ、手間でないなら、画像でもいいのよ？ｗ

**Comment by yusukebe** [comment]
帯の原稿、こんなんでいいかなー！

> YAPCではトークを聞くという楽しみもあれば、自分で発表する楽しみもあります。ためになるし、友達も増えるかも？LTはどんなネタでも基本OK。ウケなくても次ウケればいい。発表童貞を捨てるためには最適な場所ですよ。

**Comment by yusukebe** [comment]
あと、顔写真なんだけど、今のところどや顔してるこれくらいしかない！

https://dl.dropbox.com/u/9243333/IMG_1276.JPG

**Comment by uzulla** [comment]
ありがとうございます！

＞kkotaro
帯部分、なにか疑問あれば言ってください。

とりあえず、俺とゆーすけべーの物で、組んでもらえれば（後日追加予定）

**Comment by uzulla** [comment]
ちなみに、帯は10〜20人を目標に声かけ活動中です。
(返してもらえるのは、それよりは減るかなと思ってます）

**Comment by partynight12th** [comment]
帯、追加及び修正しました。
ランダムでどちらかが表示されます。
フッター部分（Closeボタン、帯、コピーライト）をクリックすると閉じたり開いたりします。
クリックしまくるの楽しいｗｗｗ

**Comment by uzulla** [comment]
帯コメはobi_text.txtに記載していく事にします。
くしいさんからコメもらいました。

**Comment by uzulla** [comment]
やばい、帯うけるｗｗｗ

**Comment by uzulla** [comment]
帯コメ更新、これで４人に。
猫型さんの写真、顔アップじゃなくてもOK（なんかそういう感じの意図を感じる写真チョイスだったので）

**Comment by makamaka** [comment]
あの丸いロゴがどーしても「えるそんてぃ」に見えてしまう……

**Comment by partynight12th** [comment]
あれ、えるそんてぃじゃないんですか？（マテ

**Comment by uzulla** [comment]
ちなみにおれもえるそんてぃに見える

**Comment by uzulla** [comment]
（まあ、あのロゴはなおしてもらおうとおもってたｗｗｗ
