### ISSUE TITLE
LTのやり方！を作成する

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapc2012-ltthon#2]
まさにLT風に作成してもらってOKだが(スライドシェアなどでもよいが)
SEO対策的にウェブページにも展開する必要がある

**Comment by uzulla** [comment]
text_howtolt.txtにメモ書きがあります。
よろしくお願いいたします！

**Comment by uzulla** [comment]
みました！

全体的に気楽さがあってもいいかと、前段のプレゼン極意はちょっと固すぎないでしょうかね？

後、まとめがあってもいいかもしれない。

ーー
最終的に、この文章はスライドではなく、テキストになっている予定ですよね？（それはOKです）
LTのYoutube動画とかうめこんだらいいかもしれないとおもいました。

**Comment by hirobanex** [comment]
ありがとうございますー！

そうですねー、前段は気合いがはいってくどくどしくなりました(笑）。全体的に、調整します。
LTのYoutube動画うめこみも対応しておきます。

「この記事を私がLTの資料すると…」みたいな感じで、スライドバージョンも作ろうかな―と思っていたんですが、現状力及ばずという感じですね(苦笑）。日曜にまた修正できたところまで、Issueに挙げさせてもらいます。

**Comment by yusukebe** [comment]
はじめて登場してみる！！！！
なんかこの場所に書いていいのか？って感じだけど！

LTとは？ってことの解説はShibuya.pmのやつがすごいいいよ！
http://shibuya.pm.org/blosxom/common/lightning_talks.html

既出だったらごめん！

**Comment by uzulla** [comment]
素晴らしい情報きたー！
（あと、この間お願いしてた「帯コメント」を、後で正式にお願いしにいきます！！もしアレなら、考えておいて頂ければ幸いです！！

**Comment by yusukebe** [comment]
あと、最近個人的にやってるのはLTとかトークの内容をBlog記事としてまとめ直すってやつっすね。
「リアルの場での発表」x「オンラインのBlog記事」っていうメディアミックスですw

例えばこれとか
http://yusukebe.com/archives/20120805/114551.html

まぁ、気になったらどこかしらにトピックとして入れこんでください！

（帯コメント了解でーす！なんか楽しそうなんで出来る限り協力しまーす）

**Comment by hirobanex** [comment]
yusukebeeさん参考情報有り難うございますっ！適宜、内容に組み入れたいと思いますっ！

> uzullaさん
> 遅くなっていて申し訳ないっす・・・
> 月曜の夜にベータバージョンにしてpushしまっす。

**Comment by uzulla** [comment]
よーし！これで火曜には仮公開できるぞー！

**Comment by uzulla** [comment]
http://www.youtube.com/user/yapcasia/videos?query=LT
こんなのもあった。

**Comment by hirobanex** [comment]
ありがとうございますっ！もろもろ参考に、ベータ版をあげましたので、ご確認ください！！

**Comment by uzulla** [comment]
（誤字脱字を除き）いいとおもいます。
とりあえずは是非掲載できる体裁に…（結構時間がない）
あとでアップデートはいくらしてもらってもOkなので。

**Comment by uzulla** [comment]
（携帯出来る体裁＝なんでもいいですけど、SlideShareにUlするとか、いまGitにあがってるHTMLを修正するとか

**Comment by hirobanex** [comment]
簡単なマークアップしてpushしました。確認お願いします。

articleのul,liやh3,h4あたりのスタイルがあたっていない都合上、「見た目がちょっと・・・」という感じなんですが、こちらはかわしまさんにお願いしても大丈夫でしょうか？僕レベルのCSS力で暫定的にあててしまうこともできるかと思うので、かわしまさんが忙しそうなら教えてくださいー。

SlideShareについて後日行います。。。

**Comment by uzulla** [comment]
HTMLで完了ならSlideShare化いらないとおもいます！

@kkotaro0111 
スタイル体裁の修正ってできます？

**Comment by uzulla** [comment]
@hirobanex 
対応むずかしいらしいので、暫定当てお願いできますでしょうか。
(まあ、フォントサイズと、Marigin-leftを調整するくらいでよいかと。

**Comment by uzulla** [comment]
といいつつ、ちょっとだけなおしておきました。
まあこれくらいになってれば読めるかなと思います。

**Comment by hirobanex** [comment]
すみませんー、ありがとうございますっ！

結構誤字脱字ありますね。。。すみません。。。

ポツポツ修正します。

**Comment by hirobanex** [comment]
がむばってスライド版もつくってつけておきましたー。他にこのissueでなければ、Closeしてもらえばですー。そのほか、別途（参加登録／スケジュール／方々への告知など）あれば声かけてくださいー。

**Comment by uzulla** [comment]
お疲れさまです！とりあえずCloseします〜
