### ISSUE TITLE
こんなLTはダメだ的LTを作成する

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapc2012-ltthon#3]
スライドで作成いただいてOK、
ただし、検索エンジンにかかるように、HTMLにも最後ひらく必要あり

**Comment by uzulla** [comment]
text_neta_howtolt.txtにメモ書きがあります。
よろしくお願いいたします！

**Comment by makamaka** [comment]
スライドってどういう感じの扱いになるんですかね？　slidshare的な共有サイトにアップしてリンク？
ネタ的なスライド（タイマーとか動的な処理）なのでどうしようかなと。

**Comment by uzulla** [comment]
私のaboutは一般さを追求してスライドシェアにあげますが、
多様性をみせてもいいかなとおもいますので、JSやYoutube埋め込みとかでもいいと思います。
（ショーケース的にも）

バネくんのテキストは結構ヘヴィーなので、あれはウェブページになるのかな？

まかまかさんのは何でやるのが一番近いですかね？

**Comment by makamaka** [comment]
パワポなら簡単かなーと思うけどそれだと見れる人限定されるので、やっぱりJSですかね。あ、携帯で録画すればyoutubeにもあげられるのか。

**Comment by uzulla** [comment]
スクリーンキャスト的なソフトで録画できるのでは？？？

**Comment by makamaka** [comment]
暫定的にslideshareにあげてリンクつけました。
色々不満があるので後で別の方法を検討するかも。

**Comment by uzulla** [comment]
お疲れ様です！
まかまかさんのスライドという一番の重要コンテンツが乗ったので、大体の体裁できましたね！
