### ISSUE TITLE
キャッチ的コピーを作成する

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/yapc2012-ltthon#4]
text_catchcopy.txtにメモ書きがあります。
よろしくお願いいたします。

**Comment by charsbar** [comment]
ごめんなさい。遅くなりました。

いまいちまとめきれなかったので、とりあえずふたつパターンを用意してみました。ひとつめは意欲はあるけど尻込みしている人が多いという前提で、追加の場を提供しますという切り口。ふたつめは話す名誉とか以前に地方主審者や中小企業勤務の人にありがちな「ぼっち」回避に協力しますよ的な切り口。もうひとつ、コミュニティ活性化のためには新しい血が…という切り口でも書いてみたのですが、まとまらなかったのでひとまず放置。いずれにしてもキャッチ的なものは詰め込みすぎない方がよいと思うので、どこかに箇条書きで詳しい要項が書かれる前提で書いています。また、治外法権的催しについてはこの段階ではキャッチには書かない方がよいと思うのでいっさい触れていません。

## 「ステージがだめなら…」

YAPCを120%楽しみたかったらトークをするに限ります。が、一般の募集枠にもう空きはなく、これから募集が行われるライトニングトークも、優に500人を越す参加者全員が集まるメイン会場で、しかも手慣れた常連スピーカーに混じっての発表になりますから、いかに5分とはいえ、初めての人にはちょっと敷居が高いかもしれません。

そこで、我々は考えました。ステージがだめならストリートでやればいいじゃない。

許可は取りました。休憩所の一角を押さえたので観客もそれなりに期待できます。発表者用のTシャツも確保済み。枠もたくさん用意しました。あとは、みなさんが5分くらい話せるネタを見つけるだけです。

LTソンに参加して、YAPC::Asiaをもっと楽しんでみませんか。

## 「ぼっちがいやなら…」

せっかくYAPC::Asiaに来ても「ぼっち」じゃ寂しいですよね。いくら懇親会があるといっても、まったく知らない人に話しかけるのは勇気がいりますし、話が弾む保証もありません。そんな心配をしているみなさんに最適なのがこのライトニングトークマラソン、略してLTソンです。ひとりに与えられる時間はだいたい5分。どんなネタでもかまいません。懇親会の会場で「あ、××の人だ」と言ってもらえるような自己紹介をしてみませんか。LTは初めてという方でも大丈夫。むしろそういう方こそいらしてください。居酒屋LT慣れしたHachioji.pmの面々や、本編の息抜きに来たPerlコミュニティのポップスターたちが、時にやさしく、時に激しく、フォローいたします。

**Comment by uzulla** [comment]
有り難うございます！
フム…
上の方がいくばくか本物感、前向き感はありますね、しかし敷居の高さが多少ある感じもあります。。
後ろのほうは、本気感が少ないですが、気楽な感じしますし…Hachioji.pm的ではありますｗ

どっちが刺さるのかなあ、

んーー
「宣伝してもらう」のを考えると、上の意識高い方がいい気もしますね。
なので、上を基本メインにしましょう。一応ファーストはマジメで。

でも下のもすばらしいですね、なので、一つ落とした所に書きましょうか。
それとも、「ところで、もし貴方がぼっちなら？」みたいなリンクを置いておいて、
たたくと入れ替わりで出てきたりするのも面白いかも。

**Comment by uzulla** [comment]
（まあ、上側がターゲットになる、比較的「意識高い」人は本編のLTにいくやろ！という気もしてはいるのですが…ｗ

**Comment by partynight12th** [comment]
叩くと入れ替わるようにしましょう！ 個人的には下の方が親しみやすかったので、ボツるのはもったいない。
ちなみにこれ、トップページのロゴの下に入れるんでいいんですよね？
ロゴの右？ だとすると長いかなぁ、と。

**Comment by uzulla** [comment]
個人的には、Tweet用文面が100文字近辺なので、それを手直しして掲載
（そして、その横にSNSのボタン設置）を考えてます。

**Comment by charsbar** [comment]
前者は前フリがいささか堅いので、適当にはしょった方がよいかもしれませんね。そのままだとロゴの右に入れるには長すぎると思うので、そちらは「ステージがだめなら…」の句だけ取り出して、「会場：多目的ホール、時間：発表者がいる限り」などの事務的な文言を付け加えるか、いっそ「All YAPC hallway are belong to us.」と書いてしまうとか。

あと、「ステージがだめなら」より「ステージがないなら」の方が元ネタが見えやすくてよかったかなという気がしています。

**Comment by uzulla** [comment]
ステージが無理なら、ステージが高すぎるならとかのほうが何となく個人的には感覚が近い。
（ないなんてことはないとおもいますし（なんだそれｗ

**Comment by charsbar** [comment]
なるほど。「高すぎるなら」というのもいいですね。

**Comment by uzulla** [comment]
とりあえず、現状でFIX？という事だとおもいますので、一旦Closeで。
Charsbarさんありがとうございました！！
